feat: add user and password to validation ping
tobiasschuerg/InfluxDB-Client-for-Arduino pull request #125
Opened 2020-12-10 15:22 UTC by moerchel

## Proposed Changes

Add user and password to the validation ping in validateConnection().
This is needed when "ping-auth-enabled" is set to true in influxdb 1.x.
When "ping-auth-enabled" is set to false the validation succeedes even when user and password are set.

## Checklist

- [ ] CHANGELOG.md updated
- [ ] Rebased/mergeable
- [ ] A test has been added if appropriate
- [ ] Tests pass
- [ ] Commit messages are in [semantic format](https://seesparkbox.com/foundry/semantic_commit_messages)

2020-12-14 08:25 UTC, vlastahajek commented
Thanks for the PR! Good improvement 👍 
I'm hesitating a bit about caching validation URL, because validation is done less frequently, most time just once, so I prefer to construct it in-place.

As querying is also used less often, so I plan to change it to lazy initialization to save RAM.

2020-12-21 14:58 UTC, vlastahajek requested changes
Please, remove caching of validation URL

2020-12-22 06:15 UTC, moerchel commented
Removed caching of validation URL

2020-12-23 10:54 UTC, vlastahajek approved these changes
Thanks!

2020-12-23 10:54 UTC, merged